Resources:
  OKElasticsearchDomain: 
    Type: AWS::Elasticsearch::Domain
    Properties:
      DomainName: "testes1"
      ElasticsearchClusterConfig: 
        InstanceCount: "1"
        InstanceType: "m3.medium.elasticsearch"
      AccessPolicies: 
        Statement: 
          - 
            Effect: "Allow"
            Action: "es:*"
            Resource: ""
            Resource: !Sub 'arn:aws:es:us-east-1:${AWS::AccountId}:domain/testes1/*'
            Principal: 
              AWS: "*"

  OKTrailBucket:
    Type: 'AWS::S3::Bucket'
    Properties: {}
  OKTrailBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref OKTrailBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: 'cloudtrail.amazonaws.com'
          Action: 's3:GetBucketAcl'
          Resource: !Sub 'arn:aws:s3:::${OKTrailBucket}'
        - Effect: Allow
          Principal:
            Service: 'cloudtrail.amazonaws.com'
          Action: 's3:PutObject'
          Resource: !Sub 'arn:aws:s3:::${OKTrailBucket}/AWSLogs/${AWS::AccountId}/*'
          Condition:
            StringEquals:
              's3:x-amz-acl': 'bucket-owner-full-control'
  Trail:
    DependsOn:
    - OKTrailBucketPolicy
    Type: 'AWS::CloudTrail::Trail'
    Properties:
      IncludeGlobalServiceEvents: true
      IsLogging: true
      IsMultiRegionTrail: true
      EventSelectors: [
        {
          DataResources: [{Type: 'AWS::S3::Object', Values: ['arn:aws:s3:::']}],
          IncludeManagementEvents: true,
          ReadWriteType: All
        }
      ]
      S3BucketName: !Ref OKTrailBucket
