AWSTemplateFormatVersion: "2010-09-09"
Description: "Gateway and Lambda function for mailgun API"

Parameters:
  myUrl:
    Type: String
    Description: Enter the URL that you got from mailgun
  myAuth:
    Type: String
    Description: Enter the Authentication api:key-xxx

Resources:
  apiGateway:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Name: "EmailThis"
      Description: "connect to lambda function"
  apiGatewayRootMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      AuthorizationType: "NONE"
      HttpMethod: "GET"
      RequestParameters:
        method.request.querystring.url: false
      MethodResponses:
      - StatusCode: 200
        ResponseModels: { "application/json": "Empty" }
      Integration:
        IntegrationHttpMethod: "POST"
        RequestTemplates:
          application/json: "{\"url\": \"$input.params('url')\"}"
        PassthroughBehavior: WHEN_NO_TEMPLATES
        ContentHandling: CONVERT_TO_TEXT
        Type: "AWS"
        IntegrationResponses:
          - StatusCode: 200
        Uri: !Sub
          - "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations"
          - lambdaArn: !GetAtt "lambdaFunction.Arn"

      ResourceId: !GetAtt "apiGateway.RootResourceId"
      RestApiId: !Ref "apiGateway"

  apiGatewayDeployment:
    Type: "AWS::ApiGateway::Deployment"
    DependsOn:
      - "apiGatewayRootMethod"
    Properties:
      RestApiId: !Ref "apiGateway"
      StageName: mycall

  lambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        ZipFile: |
          def handler(event,context):
            import urllib3
            import urllib.request
            import urllib.parse
            import json, os

            url = event['url']
            email = event.get('email', 'shantanu.oak+mailgun@gmail.com')
            title = event.get('title', 'backup')

            url1 = urllib.parse.unquote(url)
            myfile = urllib.request.urlopen(url1)

            myfile_content = myfile.read()\
                .decode(myfile.headers
                        .get_content_charset(failobj='utf-8'))

            http = urllib3.PoolManager()
            url = os.environ['myUrl'] 

            params = {"from": "Excited User <excited-user@example.com>",
                      "to": email,
                      "subject": title,
                      "text": "EmailThis service from mailgun",
                      "html": myfile_content}

            auth_headers = urllib3.util.make_headers(
                basic_auth= os.environ['myAuth'] )

            r = http.request(
                "POST",
                url,
                headers=auth_headers,
                fields=params
            )

      Description: "EmailThis"
      FunctionName: furl
      Handler: "index.handler"
      MemorySize: 128
      Role: !GetAtt "lambdaIAMRole.Arn"
      Runtime: "python3.6"
      Timeout: 10
      Environment:
        Variables:
          myUrl: !Ref myUrl
          myAuth: !Ref myAuth

  lambdaApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !GetAtt "lambdaFunction.Arn"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${apiGateway}/*/GET/"

  lambdaIAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - "sts:AssumeRole"
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
      Policies:
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Effect: "Allow"
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/furl:*"
          PolicyName: "lambda"

  lambdaLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub "/aws/lambda/furl"
      RetentionInDays: 90

Outputs:
  apiGatewayInvokeURL:
    Value: !Sub "https://${apiGateway}.execute-api.${AWS::Region}.amazonaws.com/mycall"

  lambdaArn:
    Value: !GetAtt "lambdaFunction.Arn"
